# 3.- Un quemado sirve para comunicarse solamente con quemados {-}

El uso de un teléfono quemado para hablar con el teléfono cotidiano de otra persona deja un rastro entre vos y tu contacto. Para la garantizar la privacidad de las personas dentro de tu círculo de comunicación, los teléfonos quemados solo deben usarse para comunicarse con otros teléfonos quemados, de modo que tus relaciones no comprometan tu privacidad. Hay varias formas de organizar esto, pero probablemente lo mejor sea memorizar tu propio número y compartirlo en persona con quien quieras comunicarte. Acuerden de antemano un modelo de mensaje de texto arquetípico, de modo que cuando enciendas tu teléfono puedas identificar a quien pertenece en función del mensaje y nada más. En situaciones en las que te encuentres con gente en una gran multitud, probablemente también esté bien completar este proceso con el teléfono encendido. En cualquier caso, no es necesario responder al mensaje de iniciación a menos que tengas información importante para compartir. Acordate también que es preferible que mantengas tus contactos y tus comunicaciones lo más dispersas posible, a fin de minimizar la exposición.
